// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6o_n2aCihPjKeTMN25NJxfQSAdHJe6dE',
    appId: '1:623745717856:web:1bece994786af0f8511505',
    messagingSenderId: '623745717856',
    projectId: 'seo-app-c6c22',
    authDomain: 'seo-app-c6c22.firebaseapp.com',
    storageBucket: 'seo-app-c6c22.firebasestorage.app',
    measurementId: 'G-VH0CZGML21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCujjOiXYPygkRfQIJb7X31rRrFISuzH20',
    appId: '1:623745717856:android:85a86ef945c2bbaf511505',
    messagingSenderId: '623745717856',
    projectId: 'seo-app-c6c22',
    storageBucket: 'seo-app-c6c22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCthAzloQxx2ECdvsEExM2DIMilIjn7jUo',
    appId: '1:623745717856:ios:04ca24d43e706cc8511505',
    messagingSenderId: '623745717856',
    projectId: 'seo-app-c6c22',
    storageBucket: 'seo-app-c6c22.firebasestorage.app',
    iosBundleId: 'com.example.seoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCthAzloQxx2ECdvsEExM2DIMilIjn7jUo',
    appId: '1:623745717856:ios:04ca24d43e706cc8511505',
    messagingSenderId: '623745717856',
    projectId: 'seo-app-c6c22',
    storageBucket: 'seo-app-c6c22.firebasestorage.app',
    iosBundleId: 'com.example.seoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6o_n2aCihPjKeTMN25NJxfQSAdHJe6dE',
    appId: '1:623745717856:web:7a3f00b9f4d25d24511505',
    messagingSenderId: '623745717856',
    projectId: 'seo-app-c6c22',
    authDomain: 'seo-app-c6c22.firebaseapp.com',
    storageBucket: 'seo-app-c6c22.firebasestorage.app',
    measurementId: 'G-ZZXWMDPC5G',
  );
}
